#!/bin/bash
# preflight_check.sh - Health check for AI Consultants v2.0
#
# Verifies that all consultants are available and functioning
# before starting a consultation.
#
# Usage: ./preflight_check.sh [--quick] [--json] [--suggest-config]
#
# Options:
#   --quick           Only check commands, no API tests
#   --json            Output in JSON format
#   --suggest-config  Output recommended ENABLE_* configuration

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

# --- Parameters ---
QUICK_MODE=false
JSON_OUTPUT=false
SUGGEST_CONFIG=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --quick)
            QUICK_MODE=true
            shift
            ;;
        --json)
            JSON_OUTPUT=true
            shift
            ;;
        --suggest-config)
            SUGGEST_CONFIG=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# --- State variables ---
declare -A CLI_STATUS
declare -A API_STATUS
declare -A VERSIONS
ERRORS=0
WARNINGS=0

# =============================================================================
# CHECK FUNCTIONS
# =============================================================================

check_cli_installed() {
    local name="$1"
    local cmd="$2"
    local install_hint="$3"

    if command -v "$cmd" &> /dev/null; then
        CLI_STATUS[$name]="installed"
        # Try to get version
        local version
        version=$("$cmd" --version 2>/dev/null | head -1 || echo "unknown")
        VERSIONS[$name]="$version"
        return 0
    else
        CLI_STATUS[$name]="missing"
        VERSIONS[$name]="N/A"
        ((ERRORS++))
        return 1
    fi
}

check_api_connectivity() {
    local name="$1"
    local cmd="$2"
    local test_args="$3"

    if [[ "${CLI_STATUS[$name]}" != "installed" ]]; then
        API_STATUS[$name]="skipped"
        return 1
    fi

    # Quick test with timeout
    if timeout 15 $cmd $test_args &>/dev/null; then
        API_STATUS[$name]="connected"
        return 0
    else
        API_STATUS[$name]="failed"
        ((WARNINGS++))
        return 1
    fi
}

# =============================================================================
# SUGGEST CONFIGURATION
# =============================================================================

suggest_configuration() {
    # Run quick checks first
    check_cli_installed "Gemini" "$GEMINI_CMD" "npm install -g @google/gemini-cli" || true
    check_cli_installed "Codex" "$CODEX_CMD" "npm install -g @openai/codex" || true
    check_cli_installed "Mistral" "$MISTRAL_CMD" "pip install mistral-vibe" || true
    check_cli_installed "Kilo" "$KILO_CMD" "npm install -g @kilocode/cli" || true
    check_cli_installed "Cursor" "$CURSOR_CMD" "curl https://cursor.com/install -fsS | bash" || true

    local gemini_enabled="false"
    local codex_enabled="false"
    local mistral_enabled="false"
    local kilo_enabled="false"
    local cursor_enabled="false"
    local available_count=0

    [[ "${CLI_STATUS[Gemini]:-}" == "installed" ]] && { gemini_enabled="true"; ((available_count++)); }
    [[ "${CLI_STATUS[Codex]:-}" == "installed" ]] && { codex_enabled="true"; ((available_count++)); }
    [[ "${CLI_STATUS[Mistral]:-}" == "installed" ]] && { mistral_enabled="true"; ((available_count++)); }
    [[ "${CLI_STATUS[Kilo]:-}" == "installed" ]] && { kilo_enabled="true"; ((available_count++)); }
    [[ "${CLI_STATUS[Cursor]:-}" == "installed" ]] && { cursor_enabled="true"; ((available_count++)); }

    echo "# Recommended configuration based on detected CLIs"
    echo "# Generated by: ./preflight_check.sh --suggest-config"
    echo "# Available consultants: $available_count/5"
    echo ""
    echo "ENABLE_GEMINI=$gemini_enabled"
    echo "ENABLE_CODEX=$codex_enabled"
    echo "ENABLE_MISTRAL=$mistral_enabled"
    echo "ENABLE_KILO=$kilo_enabled"
    echo "ENABLE_CURSOR=$cursor_enabled"

    if [[ $available_count -lt 2 ]]; then
        echo ""
        echo "# WARNING: Less than 2 consultants available."
        echo "# AI Consultants requires at least 2 consultants."
        echo "# Install more CLIs or run ./scripts/setup_wizard.sh"
    fi
}

# =============================================================================
# MAIN CHECKS
# =============================================================================

run_preflight() {
    if [[ "$JSON_OUTPUT" != "true" ]]; then
        echo ""
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║           AI Consultants v2.0 - Pre-flight Check             ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
    fi

    # --- Check CLI Installation ---
    if [[ "$JSON_OUTPUT" != "true" ]]; then
        echo "Checking CLI installations..."
        echo ""
    fi

    check_cli_installed "Gemini" "$GEMINI_CMD" "npm install -g @google/gemini-cli"
    check_cli_installed "Codex" "$CODEX_CMD" "npm install -g @openai/codex"
    check_cli_installed "Mistral" "$MISTRAL_CMD" "pip install mistral-vibe"
    check_cli_installed "Kilo" "$KILO_CMD" "npm install -g @kilocode/cli"
    check_cli_installed "Cursor" "$CURSOR_CMD" "curl https://cursor.com/install -fsS | bash"

    # Check for jq (required for JSON processing)
    if command -v jq &> /dev/null; then
        CLI_STATUS["jq"]="installed"
        VERSIONS["jq"]=$(jq --version 2>/dev/null || echo "unknown")
    else
        CLI_STATUS["jq"]="missing"
        VERSIONS["jq"]="N/A"
        ((ERRORS++))
    fi

    # Check for claude CLI (optional but recommended for synthesis)
    if command -v claude &> /dev/null; then
        CLI_STATUS["claude"]="installed"
        VERSIONS["claude"]=$(claude --version 2>/dev/null | head -1 || echo "unknown")
    else
        CLI_STATUS["claude"]="missing"
        VERSIONS["claude"]="N/A"
        ((WARNINGS++))  # Warning, not error - fallback available
    fi

    if [[ "$JSON_OUTPUT" != "true" ]]; then
        for name in Gemini Codex Mistral Kilo Cursor jq claude; do
            local status="${CLI_STATUS[$name]:-unknown}"
            local version="${VERSIONS[$name]:-N/A}"
            if [[ "$status" == "installed" ]]; then
                echo "  [OK] $name: $version"
            elif [[ "$name" == "claude" ]]; then
                echo "  [WARN] $name: not installed (optional)"
            else
                echo "  [FAIL] $name: NOT FOUND"
            fi
        done
        echo ""
    fi

    # --- Check API Connectivity (unless quick mode) ---
    if [[ "$QUICK_MODE" != "true" ]]; then
        if [[ "$JSON_OUTPUT" != "true" ]]; then
            echo "Testing API connectivity..."
            echo ""
        fi

        # Gemini - test with version check
        check_api_connectivity "Gemini" "$GEMINI_CMD" "--version"

        # Codex - test with help
        check_api_connectivity "Codex" "$CODEX_CMD" "--help"

        # Mistral - test with help
        check_api_connectivity "Mistral" "$MISTRAL_CMD" "--help"

        # Kilo - test with version
        check_api_connectivity "Kilo" "$KILO_CMD" "--version"

        # Cursor - test with help
        check_api_connectivity "Cursor" "$CURSOR_CMD" "--help"

        if [[ "$JSON_OUTPUT" != "true" ]]; then
            for name in Gemini Codex Mistral Kilo Cursor; do
                local status="${API_STATUS[$name]:-skipped}"
                case "$status" in
                    connected)
                        echo "  [OK] $name: API reachable"
                        ;;
                    failed)
                        echo "  [WARN] $name: API connection failed"
                        ;;
                    skipped)
                        echo "  [SKIP] $name: skipped (CLI not installed)"
                        ;;
                esac
            done
            echo ""
        fi
    fi

    # --- Check enabled consultants ---
    local enabled_count=0
    [[ "$ENABLE_GEMINI" == "true" && "${CLI_STATUS[Gemini]}" == "installed" ]] && ((enabled_count++))
    [[ "$ENABLE_CODEX" == "true" && "${CLI_STATUS[Codex]}" == "installed" ]] && ((enabled_count++))
    [[ "$ENABLE_MISTRAL" == "true" && "${CLI_STATUS[Mistral]}" == "installed" ]] && ((enabled_count++))
    [[ "$ENABLE_KILO" == "true" && "${CLI_STATUS[Kilo]}" == "installed" ]] && ((enabled_count++))
    [[ "$ENABLE_CURSOR" == "true" && "${CLI_STATUS[Cursor]}" == "installed" ]] && ((enabled_count++))

    # --- Summary ---
    if [[ "$JSON_OUTPUT" == "true" ]]; then
        # JSON output
        jq -n \
            --argjson errors "$ERRORS" \
            --argjson warnings "$WARNINGS" \
            --argjson enabled "$enabled_count" \
            --arg gemini_cli "${CLI_STATUS[Gemini]:-unknown}" \
            --arg codex_cli "${CLI_STATUS[Codex]:-unknown}" \
            --arg mistral_cli "${CLI_STATUS[Mistral]:-unknown}" \
            --arg kilo_cli "${CLI_STATUS[Kilo]:-unknown}" \
            --arg cursor_cli "${CLI_STATUS[Cursor]:-unknown}" \
            --arg jq_cli "${CLI_STATUS[jq]:-unknown}" \
            --arg claude_cli "${CLI_STATUS[claude]:-unknown}" \
            --arg gemini_api "${API_STATUS[Gemini]:-skipped}" \
            --arg codex_api "${API_STATUS[Codex]:-skipped}" \
            --arg mistral_api "${API_STATUS[Mistral]:-skipped}" \
            --arg kilo_api "${API_STATUS[Kilo]:-skipped}" \
            --arg cursor_api "${API_STATUS[Cursor]:-skipped}" \
            --arg gemini_ver "${VERSIONS[Gemini]:-N/A}" \
            --arg codex_ver "${VERSIONS[Codex]:-N/A}" \
            --arg mistral_ver "${VERSIONS[Mistral]:-N/A}" \
            --arg kilo_ver "${VERSIONS[Kilo]:-N/A}" \
            --arg cursor_ver "${VERSIONS[Cursor]:-N/A}" \
            '{
                preflight: {
                    status: (if $errors > 0 then "failed" elif $warnings > 0 then "warning" else "ok" end),
                    errors: $errors,
                    warnings: $warnings,
                    enabled_consultants: $enabled
                },
                cli: {
                    Gemini: { status: $gemini_cli, version: $gemini_ver },
                    Codex: { status: $codex_cli, version: $codex_ver },
                    Mistral: { status: $mistral_cli, version: $mistral_ver },
                    Kilo: { status: $kilo_cli, version: $kilo_ver },
                    Cursor: { status: $cursor_cli, version: $cursor_ver },
                    jq: { status: $jq_cli },
                    claude: { status: $claude_cli }
                },
                api: {
                    Gemini: $gemini_api,
                    Codex: $codex_api,
                    Mistral: $mistral_api,
                    Kilo: $kilo_api,
                    Cursor: $cursor_api
                }
            }'
    else
        echo "╔══════════════════════════════════════════════════════════════╗"
        echo "║                         Summary                              ║"
        echo "╚══════════════════════════════════════════════════════════════╝"
        echo ""
        echo "  Enabled consultants: $enabled_count/5"
        echo "  Errors: $ERRORS"
        echo "  Warnings: $WARNINGS"
        echo ""

        if [[ $ERRORS -gt 0 ]]; then
            echo "  [FAIL] Pre-flight FAILED - fix errors before proceeding"
            echo ""
            echo "  Installation hints:"
            [[ "${CLI_STATUS[Gemini]}" == "missing" ]] && echo "    npm install -g @google/gemini-cli"
            [[ "${CLI_STATUS[Codex]}" == "missing" ]] && echo "    npm install -g @openai/codex"
            [[ "${CLI_STATUS[Mistral]}" == "missing" ]] && echo "    pip install mistral-vibe"
            [[ "${CLI_STATUS[Kilo]}" == "missing" ]] && echo "    npm install -g @kilocode/cli"
            [[ "${CLI_STATUS[Cursor]}" == "missing" ]] && echo "    curl https://cursor.com/install -fsS | bash"
            [[ "${CLI_STATUS[jq]}" == "missing" ]] && echo "    brew install jq  # or apt install jq"
            echo ""
            exit 1
        elif [[ $WARNINGS -gt 0 ]]; then
            echo "  [WARN] Pre-flight PASSED with warnings"
            echo ""
            exit 0
        else
            echo "  [OK] Pre-flight PASSED - all systems go!"
            echo ""
            exit 0
        fi
    fi
}

# =============================================================================
# RUN
# =============================================================================

if [[ "$SUGGEST_CONFIG" == "true" ]]; then
    suggest_configuration
else
    run_preflight
fi
